
### Kinematic configuration parameter

# Debug mode
activate_output: false
activate_controller_node_output: false

# Clock frequency //hz
clock_frequency: 50

# Joint_names
joints_name: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint]

# Kinematic chain parameter
#chain_base_link: arm_base_link
#chain_tip_link: arm_7_link
chain_root_link: base_footprint #arm_left_base_link
target_frame: arm_left_7_target
tracking_frame: arm_left_7_link

# predictive_config: # minimum_collision_distance should not be larger than ball radius
self_collision:
     ball_radius: 0.15
     minimum_collision_distance: 0.18
     collision_weight_factor: 0.01
constraints:
     position_constraints:
           min: [-1.50, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14]
           max: [1.50, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]
     velocity_constraints:
           min: [-0.100, -0.050, -0.100, -0.050, -0.100, -0.100, -0.10]
           max: [0.100, 0.050, 0.100, 0.050, 0.100, 0.100, 0.100]
     effort_constraints:
           min: [-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0]
           max: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
     #orientation_constraints:
tolerance:
     goal_tolerance:
           # 3 position and 3 orientation tolerance
           [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
acado_config:
     max_num_iteration: 10
     kkt_tolerance: 1e-6
     integrator_tolerance: 1e-8
     start_time_horizon: 0.0
     end_time_horizon: 3.0  # control and prediction horizon
     discretization_intervals: 4
     sampling_time: 0.025
     use_lagrange_term: false
     use_LSQ_term: true
     use_mayer_term: false
     weight_factors:
           lsq_state_weight_factors:
                #always 6 component 3 linear/position and 3 angular/Euler angle
                [3.0, 3.0, 3.0, 3.0, 3.0, 3.0] #0.01
           lsq_control_weight_factors:
                # same as degree of freedom
                [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] #0.0001
