# Simulation mode
simulation_mode: false             # Is set in launch file!
gazebo_simulation: true
sync_mode: true
### Kinematic configuration parameter

# Debug mode
activate_output: true
activate_debug_output: true
activate_controller_node_output: true

# Clock frequency //hz
clock_frequency: 25

# Input and output topics
publish:
    cmd:          '/lmpcc'
    cmd_sim:      '/prius'
robot_state_topic: '/base_pose_ground_truth'
obs_state_topic: '/future'
waypoint_topic: '/path_publisher/path'
plannet_topic: '/plannet_trajectory'

# Kinematic chain parameter
robot_base_link: base_link
target_frame: map # world fixed frame but will be changed according to robot_state_topic
global_path_frame: local_car

# Parameters for predefined reference path
global_path:
  x: [0,         50, 100]
  y: [0,         0, 0]
  theta: [0, 0,  0]
  n_points_clothoid: 20
  n_points_spline: 20

#Road parameters
road_width_right: 2.15
road_width_left: 5.125

# Parameters for collision constraints
obstacles:
      n_obstacles: 2
      sub_ellipse_topic: ellipse_objects_feed
      n_discs: 3
      ego_l: 4.540
      ego_w: 1.760
                
