
### Kinematic configuration parameter

# Debug mode
activate_output: false
activate_controller_node_output: false

# Clock frequency //hz
clock_frequency: 50

# Joint_names
joints_name: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

# Kinematic chain parameter
chain_base_link: arm_base_link
chain_tip_link: arm_7_link
chain_root_link: world
target_frame: arm_7_target
tracking_frame: arm_7_link

# predictive_config: # minimum_collision_distance should not be larger than ball radius
self_collision:
     ball_radius: 0.15
     minimum_collision_distance: 0.12
     collision_weight_factor: 0.01
constraints:
     position_constraints:
           min: [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14]
           max: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]
     velocity_constraints:
           min: [-0.50, -0.20, -0.50, -0.20, -0.50, -0.50, -0.50]
           max: [0.50, 0.20, 0.50, 0.20, 0.50, 0.50, 0.50]
     effort_constraints:
           min: [-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0]
           max: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
     #orientation_constraints:
tolerance:
     goal_tolerance:
           # 3 position and 3 orientation tolerance
           [0.03, 0.01, 0.01, 0.05, 0.05, 0.05]
acado_config:
     max_num_iteration: 10
     kkt_tolerance: 1e-6
     integrator_tolerance: 1e-8
     start_time_horizon: 0.0
     end_time_horizon: 1.0
     discretization_intervals: 4
     use_lagrange_term: false
     use_LSQ_term: false
     use_mayer_term: true
