# Simulation mode
simulation_mode: false             # Is set in launch file!
gazebo_simulation: false

### Kinematic configuration parameter

# Debug mode
activate_output: true
activate_debug_output: true
activate_controller_node_output: true
plotting_result: true

# Clock frequency //hz
clock_frequency: 20

#Optimal control problem dimensions
state_dim: 5
control_dim: 2

# Input and output topics
publish:
    cmd:          '/lmpcc'
    cmd_sim:      '/prius'
robot_state_topic: '/ukf_localization_map/odometry/filtered'
obs_state_topic: '/future_obj_track'
waypoint_topic: '/path_publisher/path' 

# Kinematic chain parameter
robot_base_link: base_link
target_frame: map # world fixed frame but will be changed according to robot_state_topic
global_path_frame: local_car

# Weight on the slack variable for collision collision
slack_weight: 10000
repulsive_weight: 0.1
reference_velocity: 2.0
initial_speed: 0.0

# Parameters for predefined reference path
global_path:
  x: [0.00, -32.667, -163.245, -214.878, -283.007]
  y: [-0.13, 10.090, 41.150, 56.220, 87.35]
  theta: [2.771, 2.918, 2.918, 2.838, 2.586]
  n_points_clothoid: 20
  n_points_spline: 20

#Road parameters
road_width_right: 2.15
road_width_left: 5.125

# Parameters for collision constraints
obstacles:
      n_obstacles: 2
      sub_ellipse_topic: ellipse_objects_feed
      n_discs: 3
      ego_l: 4.540
      ego_w: 2.250

constraints:
     velocity_constraints:
           min: [0]
           max: [13.8]
     #orientation_constraints:

acado_config:
     max_num_iteration: 70
     kkt_tolerance: 1e-3
     integrator_tolerance: 1e-3
     start_time_horizon: 0.0
     end_time_horizon: 5.0 # 5.0  # control and prediction horizon
     discretization_intervals: 50
     sampling_time: 0.05
     weight_factors:
           contour_weight_factors:
                #Wcontour and Wlag
                [0.1, 0.1]
           control_weight_factors:
                # Wa and Wdelta
                [1.0, 4.0]
                
