
### Kinematic configuration parameter

# Debug mode
activate_output: false
activate_controller_node_output: false
plotting_result: true

# Clock frequency //hz
clock_frequency: 100

# Kinematic chain parameter
robot_base_link: arm_base_link
target_frame: arm_7_target
tracking_frame: arm_7_link

# predictive_config: # minimum_collision_distance should not be larger than ball radius
self_collision:
     ball_radius: 0.12
     minimum_collision_distance: 0.15
     collision_weight_factor: 0.01

     # the following links of the chain are considered for collision avoidance
     collision_check_obstacles: [arm_3_link, arm_4_link, arm_6_link]

constraints:
     velocity_constraints:
           min: [-0.50, -0.20, -0.50, -0.20, -0.50, -0.50, -0.50]
           max: [0.50, 0.20, 0.50, 0.20, 0.50, 0.50, 0.50]
     effort_constraints:
           min: [-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0]
           max: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
     #orientation_constraints:

acado_config:
     max_num_iteration: 10
     kkt_tolerance: 1e-6
     integrator_tolerance: 1e-8
     start_time_horizon: 0.0
     end_time_horizon: 3.0  # control and prediction horizon
     discretization_intervals: 4
     sampling_time: 0.025
     use_lagrange_term: false
     use_LSQ_term: true
     use_mayer_term: false
     weight_factors:
           lsq_state_weight_factors:
                #always 6 component 3 linear/position and 3 angular/Euler angle
                [5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
           lsq_control_weight_factors:
                # same as degree of freedom
                [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0]
